Repository Team-Apricot/apricot-batch-server, pull requests merged in 2024-09, with the labels that each got.

#4 [Feat] 청년 정책 API 데이터 가공 작업 및 INSERT 기능 개발
  src/main/java/sandbox/apricot/ApricotBatchApplication.java
  src/main/java/sandbox/apricot/scheduler/PolicyScheduler.java
  src/main/java/sandbox/apricot/util/AgeInfoMapper.java
  src/main/java/sandbox/apricot/util/ExtractMapper.java
  src/main/java/sandbox/apricot/util/Region.java
  src/main/java/sandbox/apricot/youth/dto/response/PolicyDto.java
  src/main/java/sandbox/apricot/youth/entity/Policy.java
  src/main/java/sandbox/apricot/youth/repository/PolicyRepository.java
  src/main/java/sandbox/apricot/youth/service/PolicyService.java
  src/main/java/sandbox/apricot/youth/service/PolicyServiceImpl.java
Labels: 🕋 DB, ✨ Feat

#5 [Facility] 미술관/박물관 API Scheduler 기능 개발
  build.gradle
  src/main/java/sandbox/apricot/artmuseum/dto/response/ArtMuseumDTO.java
  src/main/java/sandbox/apricot/artmuseum/entity/ArtMuseum.java
  src/main/java/sandbox/apricot/artmuseum/repository/ArtMuseumRepository.java
  src/main/java/sandbox/apricot/artmuseum/service/ArtMuseumService.java
  src/main/java/sandbox/apricot/artmuseum/service/ArtMuseumServiceImpl.java
  src/main/java/sandbox/apricot/scheduler/ArtMuseumScheduler.java
  src/main/java/sandbox/apricot/scheduler/PolicyScheduler.java
  src/main/java/sandbox/apricot/scheduler/UtilUpdateScheduler.java
  src/main/java/sandbox/apricot/sport/dto/response/SportDTO.java
  src/main/java/sandbox/apricot/util/EmdJSONConverter.java
  src/main/java/sandbox/apricot/util/GeomFilterConverter.java
  src/main/java/sandbox/apricot/util/MultiPolygonRegion.java
  src/main/resources/artmuseum/TL_SCCO_SIG.json
  src/main/resources/localdata/EmdCode.csv
  src/main/resources/localdata/SiGunGuCode.csv
Labels: 🍎 Chore, 🕋 DB, ✨ Feat

#7 [Add] 청년 정책 데이터 컬럼 추가
  src/main/java/sandbox/apricot/scheduler/PolicyScheduler.java
  src/main/java/sandbox/apricot/util/AgeInfoFormatter.java
  src/main/java/sandbox/apricot/util/ExtractFormatter.java
  src/main/java/sandbox/apricot/util/PeriodFormatter.java
  src/main/java/sandbox/apricot/youth/dto/response/PolicyDto.java
  src/main/java/sandbox/apricot/youth/entity/Policy.java
  src/main/java/sandbox/apricot/youth/repository/PolicyRepository.java
  src/main/java/sandbox/apricot/youth/service/PolicyServiceImpl.java
Labels: 🕋 DB

#9 [HotFix] 지역구 분류 필터링 변경
  src/main/java/sandbox/apricot/youth/service/PolicyServiceImpl.java
Labels: 🚨 HotFix, ♻️ Refactor
